print("Welcome to the tip calculator.")
bill=input("What was the total bill? $")
tip_percentage=input("What percentage tip would you like to give? 10, 12, or 15?")
number_of_people=input("How many people to split the bill?")
b = float(bill)
t = int(tip_percentage)
n = int(number_of_people)
should_pay=round(b*(1+t/100)/n,2)
print(f"Each person should pay: ${should_pay}")